name: It Will Come
favicon: null
layout_spectrum: 0.129889385541901
typography_spectrum: 0.16960796527564526
title: It Will Come
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e43753'
    - '#ffffff'
    - '#c4c4c4'
    - '#5a5a5a'
  brandStrength: 0.3965988352429122
  lightness: 0.22010300704278052
  saturation: 0.656724922824651
  rhythmicContrast: 0.4429290497209877
purpose: []
